"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { FormEvent, useState } from "react";
import { LayoutDashboard, BarChart3, Settings, Users, ChevronDown, Sparkles, Bell, Command, Plus, X } from "lucide-react";
import { OrgProvider, useOrg } from "@/lib/useOrg";
import { api } from "@/lib/api";

function CreateWorkspace({ onClose }: { onClose: () => void }) {
  const { refresh, selectOrg } = useOrg();
  const [name, setName] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setSaving(true); try { const res = await api.post("/orgs", { name }); await refresh(); selectOrg(res.data.id); onClose(); } catch (err: any) { const message = err?.response?.data?.message; setError(Array.isArray(message) ? message[0] : message ?? "We couldn't create the workspace. Try again."); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/25 p-5 backdrop-blur-sm"><form onSubmit={submit} className="glass w-full max-w-md rounded-[24px] p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-blue-600">New workspace</p><h2 className="mt-2 text-xl font-semibold text-slate-900">Create an organization</h2><p className="mt-1 text-sm text-slate-500">You’ll become the owner of this workspace.</p></div><button type="button" onClick={onClose} className="glass-soft grid h-8 w-8 place-items-center rounded-lg text-slate-500"><X size={16}/></button></div><label className="mt-6 block text-xs font-medium text-slate-600">Organization name<input required minLength={2} autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Acme Inc." className="field mt-2"/></label>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-sm font-medium text-slate-600">Cancel</button><button disabled={saving} className="glow-button rounded-xl px-4 py-2.5 text-sm font-medium text-white disabled:opacity-60">{saving ? "Creating..." : "Create workspace"}</button></div></form></div>;
}

function DashboardSidebar() {
  const pathname = usePathname(); const { orgs, orgId, selectedOrg, selectOrg, loading } = useOrg(); const [creating, setCreating] = useState(false);
  const navItems = [{ href:"/dashboard", label:"Overview", icon:LayoutDashboard }, { href:"/dashboard/analytics", label:"Analytics", icon:BarChart3 }, { href:"/dashboard/members", label:"Members", icon:Users }, { href:"/dashboard/settings", label:"Settings", icon:Settings }];
  return <aside className="sidebar relative z-10 flex w-[272px] shrink-0 flex-col border-r border-white/[.07] bg-[#070d27]/55 px-4 py-6 backdrop-blur-2xl">
    {creating && <CreateWorkspace onClose={() => setCreating(false)}/>}<Link href="/dashboard" className="mb-9 flex items-center gap-3 px-3"><span className="grid h-9 w-9 place-items-center rounded-xl glow-button"><Sparkles size={18}/></span><span className="text-lg font-semibold tracking-tight">Pulse<span className="text-blue-500">lytics</span></span></Link>
    <div className="flex items-center justify-between px-3"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#6e7da2]">Workspace</p><button onClick={() => setCreating(true)} className="flex items-center gap-1 text-xs font-semibold text-blue-600 hover:text-violet-600"><Plus size={14}/> New</button></div>
    <div className="glass-soft relative mx-1 mt-3 rounded-2xl p-2"><select value={orgId ?? ""} onChange={e=>selectOrg(e.target.value)} disabled={loading || !orgs.length} className="w-full appearance-none bg-transparent px-2 py-1 text-sm font-medium text-slate-900 outline-none"><option value="">No organizations</option>{orgs.map(org=><option className="bg-white" key={org.id} value={org.id}>{org.name}</option>)}</select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#7180a1]"/><p className="px-2 pb-1 text-[11px] capitalize text-[#7382a7]">{selectedOrg?.role ?? "Create your first workspace"}</p></div>
    <nav className="mt-8 space-y-1">{navItems.map(item=>{const active = pathname===item.href || item.href!=="/dashboard" && pathname.startsWith(item.href); return <Link key={item.href} href={item.href} className={`group flex items-center gap-3 rounded-xl px-3 py-3 text-sm transition ${active ? "bg-gradient-to-r from-blue-500/20 to-violet-500/12 text-slate-900 shadow-[inset_0_1px_rgba(255,255,255,.45)]" : "text-[#667493] hover:bg-white/55 hover:text-slate-900"}`}><item.icon size={18} className={active ? "text-[#3478f6]" : "group-hover:text-[#3478f6]"}/>{item.label}{active && <span className="ml-auto h-1.5 w-1.5 rounded-full bg-blue-500 shadow-[0_0_10px_#60a5fa]"/>}</Link>})}</nav>
    <div className="glass-soft mt-auto rounded-2xl p-4"><p className="text-xs font-medium text-slate-900">Need a hand?</p><p className="mt-1 text-[11px] leading-5 text-[#7180a1]">Discover how your product is performing.</p><button className="mt-3 flex items-center gap-1.5 text-xs font-medium text-blue-600"><Command size={13}/> View guide</button></div>
  </aside>;
}
function Topbar(){ return <header className="relative z-10 flex h-[76px] items-center justify-between border-b border-white/[.45] px-5 md:px-8"><div><p className="text-xs text-[#7180a5]">Your analytics workspace</p><p className="mt-0.5 text-sm font-medium text-slate-900">Good to see you again</p></div><div className="flex items-center gap-3"><button className="glass-soft grid h-9 w-9 place-items-center rounded-xl text-[#667493]"><Bell size={16}/></button><div className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-cyan-400 to-violet-500 text-xs font-bold text-white">VS</div></div></header> }
export default function DashboardLayout({children}:{children:React.ReactNode}){return <OrgProvider><div className="app-shell flex"><div className="noise"/><DashboardSidebar/><div className="relative z-10 min-w-0 flex-1"><Topbar/><main className="content-wrap p-5 md:p-8">{children}</main></div></div></OrgProvider>}
